version: '3.8'

services:
  chemilab-frontend:
    container_name: chemilab-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" 
    restart: unless-stopped
    networks:
      - chemilab-network

networks:
  chemilab-network:
    driver: bridge


